import { createFileRoute, Link } from "@tanstack/react-router";
import { JsonLd } from "@/components/site/json-ld";
import { breadcrumbSchema, pageHead } from "@/lib/seo";
import { guides } from "@/lib/guides";

const title = "Pay, Overtime & Career Guides — Workly USA";
const description = "Original, plain-English guides for American workers covering overtime, paychecks, PTO, salary comparisons, and job offers.";
export const Route = createFileRoute("/guides")({ head: () => pageHead({ title, description, path: "/guides" }), component: Guides });
function Guides() { return <div className="container-page py-10"><JsonLd data={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Guides", path: "/guides" }])} /><header className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-wide text-primary">Workly USA library</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-5xl">Guides to pay, hours, and work</h1><p className="mt-4 text-lg leading-relaxed text-muted-foreground">Practical explanations to help you understand your paycheck, compare opportunities, and ask better questions at work.</p><p className="mt-4 text-sm text-muted-foreground">Written and reviewed by the Workly USA editorial team. Articles show their last updated date and are general information, not professional advice.</p></header><div className="mt-12 grid gap-5 md:grid-cols-2">{guides.map((guide) => <article key={guide.slug} className="rounded-2xl border border-border bg-card p-6 shadow-card"><p className="text-xs font-semibold uppercase tracking-wide text-primary">{guide.category}</p><h2 className="mt-2 font-display text-xl font-semibold"><Link to="/guide/$slug" params={{ slug: guide.slug }} className="hover:text-primary">{guide.title}</Link></h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{guide.summary}</p><p className="mt-5 text-xs text-muted-foreground">Updated {guide.updated}</p><Link to="/guide/$slug" params={{ slug: guide.slug }} className="mt-4 inline-block text-sm font-semibold text-primary hover:underline">Read the guide →</Link></article>)}</div><p className="mt-12 max-w-3xl rounded-xl border border-border bg-surface p-5 text-xs leading-relaxed text-muted-foreground">Pay, tax, and employment rules can change and may differ by state. Check current guidance from the U.S. Department of Labor, IRS, your state labor department, or a qualified professional.</p></div>; }
