import {
  ArrowDownRight,
  ArrowUpRight,
  Briefcase,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarDays,
  Car,
  ClipboardList,
  Clock,
  Coffee,
  Coins,
  Compass,
  Gauge,
  Gift,
  GitCompareArrows,
  MapPin,
  Moon,
  Percent,
  PiggyBank,
  Plane,
  Scale,
  Sunrise,
  Timer,
  TrendingUp,
  Umbrella,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  ArrowDownRight,
  ArrowUpRight,
  Briefcase,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarDays,
  Car,
  ClipboardList,
  Clock,
  Coffee,
  Coins,
  Compass,
  Gauge,
  Gift,
  GitCompareArrows,
  MapPin,
  Moon,
  Percent,
  PiggyBank,
  Plane,
  Scale,
  Sunrise,
  Timer,
  TrendingUp,
  Umbrella,
  Wallet,
  Zap,
};

export function ToolIcon({ name, className }: { name: string; className?: string }) {
  const Component = registry[name] ?? Calculator;
  return <Component className={className} aria-hidden="true" />;
}
