/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AllToolsRouteImport } from './routes/all-tools'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EditorialStandardsRouteImport } from './routes/editorial-standards'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as JobOfferChecklistRouteImport } from './routes/job-offer-checklist'
import { Route as PayStubGlossaryRouteImport } from './routes/pay-stub-glossary'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as GuideSlugRouteImport } from './routes/guide.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AllToolsRoute = AllToolsRouteImport.update({
  id: '/all-tools',
  path: '/all-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialStandardsRoute = EditorialStandardsRouteImport.update({
  id: '/editorial-standards',
  path: '/editorial-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const JobOfferChecklistRoute = JobOfferChecklistRouteImport.update({
  id: '/job-offer-checklist',
  path: '/job-offer-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const PayStubGlossaryRoute = PayStubGlossaryRouteImport.update({
  id: '/pay-stub-glossary',
  path: '/pay-stub-glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideSlugRoute = GuideSlugRouteImport.update({
  id: '/guide/$slug',
  path: '/guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/all-tools': typeof AllToolsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/guides': typeof GuidesRoute
  '/job-offer-checklist': typeof JobOfferChecklistRoute
  '/pay-stub-glossary': typeof PayStubGlossaryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/guide/$slug': typeof GuideSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/all-tools': typeof AllToolsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/guides': typeof GuidesRoute
  '/job-offer-checklist': typeof JobOfferChecklistRoute
  '/pay-stub-glossary': typeof PayStubGlossaryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/guide/$slug': typeof GuideSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/all-tools': typeof AllToolsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/guides': typeof GuidesRoute
  '/job-offer-checklist': typeof JobOfferChecklistRoute
  '/pay-stub-glossary': typeof PayStubGlossaryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/guide/$slug': typeof GuideSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/all-tools'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/editorial-standards'
    | '/guides'
    | '/job-offer-checklist'
    | '/pay-stub-glossary'
    | '/privacy-policy'
    | '/terms'
    | '/category/$category'
    | '/guide/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/all-tools'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/editorial-standards'
    | '/guides'
    | '/job-offer-checklist'
    | '/pay-stub-glossary'
    | '/privacy-policy'
    | '/terms'
    | '/category/$category'
    | '/guide/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/all-tools'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/editorial-standards'
    | '/guides'
    | '/job-offer-checklist'
    | '/pay-stub-glossary'
    | '/privacy-policy'
    | '/terms'
    | '/category/$category'
    | '/guide/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AllToolsRoute: typeof AllToolsRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EditorialStandardsRoute: typeof EditorialStandardsRoute
  GuidesRoute: typeof GuidesRoute
  JobOfferChecklistRoute: typeof JobOfferChecklistRoute
  PayStubGlossaryRoute: typeof PayStubGlossaryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  GuideSlugRoute: typeof GuideSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-tools': {
      id: '/all-tools'
      path: '/all-tools'
      fullPath: '/all-tools'
      preLoaderRoute: typeof AllToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-standards': {
      id: '/editorial-standards'
      path: '/editorial-standards'
      fullPath: '/editorial-standards'
      preLoaderRoute: typeof EditorialStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-offer-checklist': {
      id: '/job-offer-checklist'
      path: '/job-offer-checklist'
      fullPath: '/job-offer-checklist'
      preLoaderRoute: typeof JobOfferChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-stub-glossary': {
      id: '/pay-stub-glossary'
      path: '/pay-stub-glossary'
      fullPath: '/pay-stub-glossary'
      preLoaderRoute: typeof PayStubGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$slug': {
      id: '/guide/$slug'
      path: '/guide/$slug'
      fullPath: '/guide/$slug'
      preLoaderRoute: typeof GuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AllToolsRoute: AllToolsRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  EditorialStandardsRoute: EditorialStandardsRoute,
  GuidesRoute: GuidesRoute,
  JobOfferChecklistRoute: JobOfferChecklistRoute,
  PayStubGlossaryRoute: PayStubGlossaryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  GuideSlugRoute: GuideSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
